set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/vimfiles/bundle/Vundle.vim
call vundle#begin('~/vimfiles/')
Plugin 'VundleVim/Vundle.vim'

Plugin 'L9'
Plugin 'sjl/badwolf'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'bling/vim-airline'
Plugin 'mattn/emmet-vim'
Plugin 'Shougo/neocomplcache.vim'

call vundle#end()            " required
filetype plugin indent on    " required

" Colors {{{
syntax enable           " enable syntax processing
colorscheme badwolf
" }}}

" Misc {{{
set ttyfast                     " faster redraw
set backspace=indent,eol,start
set guifont=Source_Code_Pro:h14

if has("multi_byte")
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  "setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

" }}}

" Spaces & Tabs {{{
set tabstop=4           " 4 space tab
set expandtab           " use spaces for tabs
set softtabstop=4       " 4 space tab
set shiftwidth=4
set modelines=1
filetype indent on
filetype plugin on
set autoindent
" }}}

" UI Layout {{{
set number              " show line numbers
set showcmd             " show command in bottom bar
set nocursorline        " highlight current line
set wildmenu
set lazyredraw
set showmatch           " higlight matching parenthesis
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
" }}}

" Searching {{{
set ignorecase          " ignore case when searching
set incsearch           " search as characters are entered
set hlsearch            " highlight all matches
" }}}

" Folding {{{
"=== folding ===
set foldmethod=indent   " fold based on indent level
set foldnestmax=10      " max 10 depth
set foldenable          " don't fold files by default on open
nnoremap <space> za
set foldlevelstart=10    " start with fold level of 1
" }}}

" Leader Shortcuts {{{
let mapleader=","
nnoremap <c-e> :NERDTreeToggle<CR>
nnoremap <c-f> :NERDTreeFind<CR>
nnoremap <c-p> :CtrlPBuffer<CR>
nmap <c-t> :TagbarToggle<CR>
inoremap <Nul> <C-p>
"}}}

" Others Shortcuts {{{
map <F11> <Esc>:call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)<CR> 
" }}}

" Plugins Configurations {{{

" CtrlP {{{
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_by_filename = 1
" }}}

" Syntastic {{{
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
"}}}

" Emmet {{{
let g:user_emmet_leader_key='<C-Z>'
let g:user_emmet_install_global = 0
let g:user_emmet_mode='a'
autocmd FileType html,css EmmetInstall
" }}}

" NeoComplCache {{{
let g:neocomplcache_enable_at_startup = 1
" }}}

" }}}
