filetype indent on
filetype plugin on

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'mattn/emmet-vim'
Plugin 'bronson/vim-trailing-whitespace'
call vundle#end()


" Misc {{{
syntax off
set nu
set noswapfile
set background=light
set ttyfast
set backspace=indent,eol,start
set clipboard=unnamedplus
set splitbelow
set splitright
set autoindent
set smartindent
set mouse=a
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set modelines=1
set cursorline
set showmatch
set lazyredraw
set path+=**
set ignorecase
set incsearch
set nohlsearch
set wildmenu
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/.git/*,*/.hg/*,*/vendor/*,*/bower_components/*,*/node_modules/*

" Shortcuts
map <C-e> :NERDTreeToggle<CR>
map <C-p> <Esc>:find 

" Ctrl + HJKL movement
nmap <C-k> :wincmd k<CR>
nmap <C-j> :wincmd j<CR>
nmap <C-h> :wincmd h<CR>
nmap <C-l> :wincmd l<CR>

" Tab control
nnoremap <C-t> :sp<CR>
inoremap <C-t> <Esc>:sp<CR>
